// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: proto/agentdiscovery/agentdiscovery.proto

package agentdiscovery

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentDiscoveryPayloadBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payloads []*AgentDiscoveryPayload `protobuf:"bytes,1,rep,name=payloads,proto3" json:"payloads,omitempty"`
}

func (x *AgentDiscoveryPayloadBatch) Reset() {
	*x = AgentDiscoveryPayloadBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agentdiscovery_agentdiscovery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentDiscoveryPayloadBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDiscoveryPayloadBatch) ProtoMessage() {}

func (x *AgentDiscoveryPayloadBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentdiscovery_agentdiscovery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDiscoveryPayloadBatch.ProtoReflect.Descriptor instead.
func (*AgentDiscoveryPayloadBatch) Descriptor() ([]byte, []int) {
	return file_proto_agentdiscovery_agentdiscovery_proto_rawDescGZIP(), []int{0}
}

func (x *AgentDiscoveryPayloadBatch) GetPayloads() []*AgentDiscoveryPayload {
	if x != nil {
		return x.Payloads
	}
	return nil
}

type AgentDiscoveryPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Integration string                  `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
	ServiceId   string                  `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Runtime     string                  `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Configs     []*AgentDiscoveryConfig `protobuf:"bytes,4,rep,name=configs,proto3" json:"configs,omitempty"`
}

func (x *AgentDiscoveryPayload) Reset() {
	*x = AgentDiscoveryPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agentdiscovery_agentdiscovery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentDiscoveryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDiscoveryPayload) ProtoMessage() {}

func (x *AgentDiscoveryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentdiscovery_agentdiscovery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDiscoveryPayload.ProtoReflect.Descriptor instead.
func (*AgentDiscoveryPayload) Descriptor() ([]byte, []int) {
	return file_proto_agentdiscovery_agentdiscovery_proto_rawDescGZIP(), []int{1}
}

func (x *AgentDiscoveryPayload) GetIntegration() string {
	if x != nil {
		return x.Integration
	}
	return ""
}

func (x *AgentDiscoveryPayload) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *AgentDiscoveryPayload) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *AgentDiscoveryPayload) GetConfigs() []*AgentDiscoveryConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type AgentDiscoveryConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Path      string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content   []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Truncated bool   `protobuf:"varint,4,opt,name=truncated,proto3" json:"truncated,omitempty"`
}

func (x *AgentDiscoveryConfig) Reset() {
	*x = AgentDiscoveryConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_agentdiscovery_agentdiscovery_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentDiscoveryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDiscoveryConfig) ProtoMessage() {}

func (x *AgentDiscoveryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentdiscovery_agentdiscovery_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDiscoveryConfig.ProtoReflect.Descriptor instead.
func (*AgentDiscoveryConfig) Descriptor() ([]byte, []int) {
	return file_proto_agentdiscovery_agentdiscovery_proto_rawDescGZIP(), []int{2}
}

func (x *AgentDiscoveryConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentDiscoveryConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AgentDiscoveryConfig) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *AgentDiscoveryConfig) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

var File_proto_agentdiscovery_agentdiscovery_proto protoreflect.FileDescriptor

var file_proto_agentdiscovery_agentdiscovery_proto_rawDesc = []byte{
	0x0a, 0x29, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x64, 0x69, 0x73, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x64, 0x61, 0x74,
	0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x79, 0x22, 0x67, 0x0a, 0x1a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x79, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x49, 0x0a, 0x08, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x08, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x22, 0xba, 0x01, 0x0a,
	0x15, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x74,
	0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x46, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x64, 0x6f, 0x67, 0x2e, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x22, 0x76, 0x0a, 0x14, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72, 0x75, 0x6e, 0x63, 0x61, 0x74, 0x65, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x74, 0x72, 0x75, 0x6e, 0x63, 0x61, 0x74, 0x65,
	0x64, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x44, 0x61, 0x74, 0x61, 0x44, 0x6f, 0x67, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2d, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2f, 0x76, 0x35, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x64, 0x69,
	0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_agentdiscovery_agentdiscovery_proto_rawDescOnce sync.Once
	file_proto_agentdiscovery_agentdiscovery_proto_rawDescData = file_proto_agentdiscovery_agentdiscovery_proto_rawDesc
)

func file_proto_agentdiscovery_agentdiscovery_proto_rawDescGZIP() []byte {
	file_proto_agentdiscovery_agentdiscovery_proto_rawDescOnce.Do(func() {
		file_proto_agentdiscovery_agentdiscovery_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_agentdiscovery_agentdiscovery_proto_rawDescData)
	})
	return file_proto_agentdiscovery_agentdiscovery_proto_rawDescData
}

var file_proto_agentdiscovery_agentdiscovery_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_agentdiscovery_agentdiscovery_proto_goTypes = []interface{}{
	(*AgentDiscoveryPayloadBatch)(nil), // 0: datadog.agentdiscovery.AgentDiscoveryPayloadBatch
	(*AgentDiscoveryPayload)(nil),      // 1: datadog.agentdiscovery.AgentDiscoveryPayload
	(*AgentDiscoveryConfig)(nil),       // 2: datadog.agentdiscovery.AgentDiscoveryConfig
}
var file_proto_agentdiscovery_agentdiscovery_proto_depIdxs = []int32{
	1, // 0: datadog.agentdiscovery.AgentDiscoveryPayloadBatch.payloads:type_name -> datadog.agentdiscovery.AgentDiscoveryPayload
	2, // 1: datadog.agentdiscovery.AgentDiscoveryPayload.configs:type_name -> datadog.agentdiscovery.AgentDiscoveryConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_agentdiscovery_agentdiscovery_proto_init() }
func file_proto_agentdiscovery_agentdiscovery_proto_init() {
	if File_proto_agentdiscovery_agentdiscovery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_agentdiscovery_agentdiscovery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentDiscoveryPayloadBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agentdiscovery_agentdiscovery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentDiscoveryPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_agentdiscovery_agentdiscovery_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentDiscoveryConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_agentdiscovery_agentdiscovery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_agentdiscovery_agentdiscovery_proto_goTypes,
		DependencyIndexes: file_proto_agentdiscovery_agentdiscovery_proto_depIdxs,
		MessageInfos:      file_proto_agentdiscovery_agentdiscovery_proto_msgTypes,
	}.Build()
	File_proto_agentdiscovery_agentdiscovery_proto = out.File
	file_proto_agentdiscovery_agentdiscovery_proto_rawDesc = nil
	file_proto_agentdiscovery_agentdiscovery_proto_goTypes = nil
	file_proto_agentdiscovery_agentdiscovery_proto_depIdxs = nil
}
