[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "=v1.0.0"

[[constraint]]
  name = "github.com/DataDog/zstd_0"
  revision = "586c1286621ffa183e6b66eb1df0aa52596b5ca2"

[[constraint]]
  name = "github.com/DataDog/mmh3"
  version = "^1.0.0"