// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/contlcycle/contlcycle.proto

/*
	Package contlcycle is a generated protocol buffer package.

	It is generated from these files:
		proto/contlcycle/contlcycle.proto

	It has these top-level messages:
		EventsPaylaod
		Event
*/
package contlcycle

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type EventsPaylaod_EventType int32

const (
	EventsPaylaod_Delete EventsPaylaod_EventType = 0
)

var EventsPaylaod_EventType_name = map[int32]string{
	0: "Delete",
}
var EventsPaylaod_EventType_value = map[string]int32{
	"Delete": 0,
}

func (x EventsPaylaod_EventType) String() string {
	return proto.EnumName(EventsPaylaod_EventType_name, int32(x))
}
func (EventsPaylaod_EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorContlcycle, []int{0, 0}
}

type EventsPaylaod_ObjectKind int32

const (
	EventsPaylaod_Cont EventsPaylaod_ObjectKind = 0
	EventsPaylaod_Pod  EventsPaylaod_ObjectKind = 1
)

var EventsPaylaod_ObjectKind_name = map[int32]string{
	0: "Cont",
	1: "Pod",
}
var EventsPaylaod_ObjectKind_value = map[string]int32{
	"Cont": 0,
	"Pod":  1,
}

func (x EventsPaylaod_ObjectKind) String() string {
	return proto.EnumName(EventsPaylaod_ObjectKind_name, int32(x))
}
func (EventsPaylaod_ObjectKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorContlcycle, []int{0, 1}
}

// EventsPaylaod represents the main container lifecycle event payload
type EventsPaylaod struct {
	Version    string                   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	EventType  EventsPaylaod_EventType  `protobuf:"varint,2,opt,name=eventType,proto3,enum=datadog.contlcycle.EventsPaylaod_EventType" json:"eventType,omitempty"`
	ObjectKind EventsPaylaod_ObjectKind `protobuf:"varint,3,opt,name=objectKind,proto3,enum=datadog.contlcycle.EventsPaylaod_ObjectKind" json:"objectKind,omitempty"`
	Host       string                   `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Events     []*Event                 `protobuf:"bytes,5,rep,name=events" json:"events,omitempty"`
}

func (m *EventsPaylaod) Reset()                    { *m = EventsPaylaod{} }
func (m *EventsPaylaod) String() string            { return proto.CompactTextString(m) }
func (*EventsPaylaod) ProtoMessage()               {}
func (*EventsPaylaod) Descriptor() ([]byte, []int) { return fileDescriptorContlcycle, []int{0} }

func (m *EventsPaylaod) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *EventsPaylaod) GetEventType() EventsPaylaod_EventType {
	if m != nil {
		return m.EventType
	}
	return EventsPaylaod_Delete
}

func (m *EventsPaylaod) GetObjectKind() EventsPaylaod_ObjectKind {
	if m != nil {
		return m.ObjectKind
	}
	return EventsPaylaod_Cont
}

func (m *EventsPaylaod) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *EventsPaylaod) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

// Event contains the details about a container lifecycle event
type Event struct {
	ObjectID      string `protobuf:"bytes,1,opt,name=objectID,proto3" json:"objectID,omitempty"`
	Source        string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	ExitCode      int32  `protobuf:"varint,3,opt,name=exitCode,proto3" json:"exitCode,omitempty"`
	ExitTimestamp int64  `protobuf:"varint,4,opt,name=exitTimestamp,proto3" json:"exitTimestamp,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptorContlcycle, []int{1} }

func (m *Event) GetObjectID() string {
	if m != nil {
		return m.ObjectID
	}
	return ""
}

func (m *Event) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Event) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *Event) GetExitTimestamp() int64 {
	if m != nil {
		return m.ExitTimestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*EventsPaylaod)(nil), "datadog.contlcycle.EventsPaylaod")
	proto.RegisterType((*Event)(nil), "datadog.contlcycle.Event")
	proto.RegisterEnum("datadog.contlcycle.EventsPaylaod_EventType", EventsPaylaod_EventType_name, EventsPaylaod_EventType_value)
	proto.RegisterEnum("datadog.contlcycle.EventsPaylaod_ObjectKind", EventsPaylaod_ObjectKind_name, EventsPaylaod_ObjectKind_value)
}
func (m *EventsPaylaod) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventsPaylaod) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Version) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintContlcycle(dAtA, i, uint64(len(m.Version)))
		i += copy(dAtA[i:], m.Version)
	}
	if m.EventType != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintContlcycle(dAtA, i, uint64(m.EventType))
	}
	if m.ObjectKind != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintContlcycle(dAtA, i, uint64(m.ObjectKind))
	}
	if len(m.Host) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintContlcycle(dAtA, i, uint64(len(m.Host)))
		i += copy(dAtA[i:], m.Host)
	}
	if len(m.Events) > 0 {
		for _, msg := range m.Events {
			dAtA[i] = 0x2a
			i++
			i = encodeVarintContlcycle(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *Event) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Event) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ObjectID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintContlcycle(dAtA, i, uint64(len(m.ObjectID)))
		i += copy(dAtA[i:], m.ObjectID)
	}
	if len(m.Source) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintContlcycle(dAtA, i, uint64(len(m.Source)))
		i += copy(dAtA[i:], m.Source)
	}
	if m.ExitCode != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintContlcycle(dAtA, i, uint64(m.ExitCode))
	}
	if m.ExitTimestamp != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintContlcycle(dAtA, i, uint64(m.ExitTimestamp))
	}
	return i, nil
}

func encodeVarintContlcycle(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *EventsPaylaod) Size() (n int) {
	var l int
	_ = l
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovContlcycle(uint64(l))
	}
	if m.EventType != 0 {
		n += 1 + sovContlcycle(uint64(m.EventType))
	}
	if m.ObjectKind != 0 {
		n += 1 + sovContlcycle(uint64(m.ObjectKind))
	}
	l = len(m.Host)
	if l > 0 {
		n += 1 + l + sovContlcycle(uint64(l))
	}
	if len(m.Events) > 0 {
		for _, e := range m.Events {
			l = e.Size()
			n += 1 + l + sovContlcycle(uint64(l))
		}
	}
	return n
}

func (m *Event) Size() (n int) {
	var l int
	_ = l
	l = len(m.ObjectID)
	if l > 0 {
		n += 1 + l + sovContlcycle(uint64(l))
	}
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovContlcycle(uint64(l))
	}
	if m.ExitCode != 0 {
		n += 1 + sovContlcycle(uint64(m.ExitCode))
	}
	if m.ExitTimestamp != 0 {
		n += 1 + sovContlcycle(uint64(m.ExitTimestamp))
	}
	return n
}

func sovContlcycle(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozContlcycle(x uint64) (n int) {
	return sovContlcycle(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventsPaylaod) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContlcycle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventsPaylaod: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventsPaylaod: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContlcycle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContlcycle
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventType", wireType)
			}
			m.EventType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContlcycle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EventType |= (EventsPaylaod_EventType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectKind", wireType)
			}
			m.ObjectKind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContlcycle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ObjectKind |= (EventsPaylaod_ObjectKind(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Host", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContlcycle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContlcycle
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Host = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Events", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContlcycle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthContlcycle
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Events = append(m.Events, &Event{})
			if err := m.Events[len(m.Events)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContlcycle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthContlcycle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Event) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContlcycle
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Event: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Event: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContlcycle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContlcycle
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ObjectID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContlcycle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContlcycle
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExitCode", wireType)
			}
			m.ExitCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContlcycle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExitCode |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExitTimestamp", wireType)
			}
			m.ExitTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContlcycle
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExitTimestamp |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipContlcycle(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthContlcycle
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipContlcycle(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowContlcycle
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContlcycle
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContlcycle
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthContlcycle
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowContlcycle
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipContlcycle(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthContlcycle = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowContlcycle   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("proto/contlcycle/contlcycle.proto", fileDescriptorContlcycle) }

var fileDescriptorContlcycle = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x41, 0x4f, 0xea, 0x40,
	0x10, 0xc7, 0x29, 0x85, 0x42, 0xe7, 0x85, 0x17, 0x32, 0x87, 0xf7, 0xaa, 0x07, 0xc4, 0xc6, 0x03,
	0x89, 0xda, 0x46, 0x8c, 0x37, 0x4f, 0x52, 0x0f, 0x44, 0x13, 0x49, 0xc3, 0xc9, 0xdb, 0xd2, 0xdd,
	0x94, 0x9a, 0xd2, 0x69, 0xe8, 0x42, 0xec, 0xc1, 0x4f, 0xe7, 0xc5, 0xa3, 0x1f, 0xc1, 0xf0, 0x49,
	0x4c, 0x17, 0x2c, 0x10, 0x63, 0xbc, 0xcd, 0x7f, 0x67, 0x7e, 0xff, 0x99, 0x9d, 0x0c, 0x1c, 0xa7,
	0x73, 0x92, 0xe4, 0x06, 0x94, 0xc8, 0x38, 0xc8, 0x83, 0x58, 0xec, 0x84, 0x8e, 0xca, 0x21, 0x72,
	0x26, 0x19, 0xa7, 0xd0, 0xd9, 0x66, 0xec, 0xd7, 0x2a, 0xb4, 0x6e, 0x97, 0x22, 0x91, 0xd9, 0x88,
	0xe5, 0x31, 0x23, 0x8e, 0x16, 0x34, 0x96, 0x62, 0x9e, 0x45, 0x94, 0x58, 0x5a, 0x57, 0xeb, 0x99,
	0xfe, 0x97, 0xc4, 0x21, 0x98, 0xa2, 0x28, 0x1d, 0xe7, 0xa9, 0xb0, 0xaa, 0x5d, 0xad, 0xf7, 0xb7,
	0x7f, 0xea, 0x7c, 0xf7, 0x74, 0xf6, 0xfc, 0xd6, 0xaa, 0x40, 0xfc, 0x2d, 0x8d, 0xf7, 0x00, 0x34,
	0x79, 0x12, 0x81, 0xbc, 0x8b, 0x12, 0x6e, 0xe9, 0xca, 0xeb, 0xec, 0x77, 0xaf, 0x87, 0x92, 0xf1,
	0x77, 0x78, 0x44, 0xa8, 0x4d, 0x29, 0x93, 0x56, 0x4d, 0xcd, 0xab, 0x62, 0xbc, 0x00, 0x43, 0xb5,
	0xcb, 0xac, 0x7a, 0x57, 0xef, 0xfd, 0xe9, 0x1f, 0xfc, 0xe8, 0xee, 0x6f, 0x0a, 0xed, 0xff, 0x60,
	0x96, 0xc3, 0x22, 0x80, 0xe1, 0x89, 0x58, 0x48, 0xd1, 0xae, 0xd8, 0x47, 0x00, 0xdb, 0xce, 0xd8,
	0x84, 0xda, 0x80, 0x12, 0xd9, 0xae, 0x60, 0x03, 0xf4, 0x11, 0xf1, 0xb6, 0x66, 0xbf, 0x40, 0x5d,
	0x91, 0x78, 0x08, 0xcd, 0xf5, 0x5c, 0x43, 0x6f, 0xb3, 0xbd, 0x52, 0xe3, 0x3f, 0x30, 0x32, 0x5a,
	0xcc, 0x83, 0xf5, 0xee, 0x4c, 0x7f, 0xa3, 0x0a, 0x46, 0x3c, 0x47, 0x72, 0x40, 0x5c, 0xa8, 0x4d,
	0xd4, 0xfd, 0x52, 0xe3, 0x09, 0xb4, 0x8a, 0x78, 0x1c, 0xcd, 0x44, 0x26, 0xd9, 0x2c, 0x55, 0x5f,
	0xd4, 0xfd, 0xfd, 0xc7, 0x9b, 0xeb, 0xb7, 0x55, 0x47, 0x7b, 0x5f, 0x75, 0xb4, 0x8f, 0x55, 0x47,
	0x7b, 0x74, 0xc2, 0x48, 0x4e, 0x17, 0x13, 0x27, 0xa0, 0x99, 0xeb, 0x31, 0xc9, 0x3c, 0x0a, 0x5d,
	0x16, 0x8a, 0x44, 0x9e, 0xa7, 0x2c, 0x8f, 0x89, 0x71, 0x77, 0x79, 0xb5, 0x73, 0x1c, 0x13, 0x43,
	0x5d, 0xc7, 0xe5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xd3, 0xfc, 0xd2, 0x42, 0x02, 0x00,
	0x00,
}
