// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agent_logs_payload.proto

package com.dd.agent.pb;

public interface LogPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.LogPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pb.Log log = 1;</code>
   */
  boolean hasLog();
  /**
   * <code>.pb.Log log = 1;</code>
   */
  com.dd.agent.pb.Log getLog();
  /**
   * <code>.pb.Log log = 1;</code>
   */
  com.dd.agent.pb.LogOrBuilder getLogOrBuilder();

  /**
   * <pre>
   * </pre>
   *
   * <code>string api_key = 2;</code>
   */
  java.lang.String getApiKey();
  /**
   * <pre>
   * </pre>
   *
   * <code>string api_key = 2;</code>
   */
  com.google.protobuf.ByteString
      getApiKeyBytes();

  /**
   * <pre>
   * will disappear one day
   * </pre>
   *
   * <code>string logset = 3;</code>
   */
  java.lang.String getLogset();
  /**
   * <pre>
   * will disappear one day
   * </pre>
   *
   * <code>string logset = 3;</code>
   */
  com.google.protobuf.ByteString
      getLogsetBytes();
}
